# Generated by Django 3.0.6 on 2024-01-24 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20240124_1222'),
        ('stores', '0002_store'),
    ]

    operations = [
    ]
